beem/blockchain.py

* remove redundant `Block()` calls
* don't wait `block_interval` seconds before raising the exception

wait_for_and_get_block refactoring

---

beem/account.py

Fixes #18 
Please review these carefully, I'm not sure I covered all cases. The PR includes changes also to `account_history_reverse()`, which does not fail with the example in #18.

Fix account history calls for op 0

---

beemgraphenebase/chains.py

VIT is a Steem fork that should be fully plug-and-play with Beem given the `chains.py` file is updated to recognize the new chain id.

Add VIT to known_chains

---

beem/discussions.py

`start_parent_author` parameter was missing in the RPC call and the
Query class.
Fixes #52

fix discussions.Replies_by_last_update()

---

beem/discussions.py

setting `set_next_node_on_empty_reply` for Discussions_by_feed and
Discussions_by_comments
Fixes #54

discussions: allow empty replies

---

beem/account.py
beem/steem.py

This pull request adds a very small tweak to the vote value calculations if it is set to True. It does this by extending the recent_claims with the rshares of the vote that shall be calculated. This has little to no impact for small votes, but the impact gets higher, the bigger the vote is (as of now, the @steemit vote value changes about 10 $, which still is very small in comparison to the total vote value.) This also fixes a semi-bug if used, that the vote of a absolutely huge account seems to exceed the reward pool in value, even though that's not possible (this might have been a real bug in the very early days of steem)

new_vote flag for vote value calculations

---

beem/account.py
beem/steem.py
tests/beem/test_account.py
tests/beem/test_steem.py

Should be self explanatory when looking at the documentation. Adds three new functions:
1. `get_vote_pct_for_SBD`
This function takes a number/string/Amount object as a parameter and returns the voting percentage needed to get a vote worth the earlier provided amount of SBD.
2. `sbd_to_vote_pct`
Very similar to `get_vote_pct_for_SBD`. Essentially does the same, but isn't part of the account module, but part of the steem module.
3. `sbd_to_rshares`
Returns an estimation of the number of required rshares for getting the value of the provided sbd.

Add get_vote_pct_for_SBD, sbd_to_vote_pct and sbd_to_rshares

---

beem/steem.py

It was slightly unclear that one of the two required auths were needed since both also say optional. Added a note explaining the need for one of the two as well as a block of pseudocode to display the message further.

Added an example to the custom_json section for documentation.

---

beembase/objects.py

Refs #72
* serialization of appbase Amounts was incorrect (used `nai` number instead of `symbol` name)
* serialization of appbase beneficiary objects.
I'm pretty sure this doesn't fix the problem for custom chain params provided to the `Steem()` constructor but at least it should do for chains contained in `beemgraphenebase/chains.py`

beembase/objects: fix serialization of appbase trx

---

beem/steem.py

We can get rid of the iterative approach by utilizing a few formulars. This makes the function signature smaller as well as improving performance drastically while increasing the precision. 
I also added a few comments to make it more obvious what I'm doing here.

Optimize sbd_to_rshares to not use an iterative approach

---

beem/steem.py

In HF20 every vote will get 50 000 000 rshares subtracted, and this PR makes these changes apply to calculations such as `vests_to_rshares`

Make vote rshare calculations HF20 ready

---

beem/account.py
beem/comment.py
beem/snapshot.py
beem/steem.py
beem/witness.py
beembase/objects.py
beembase/operations.py

These commits introduce `steem.steem_symbol`, `steem.sbd_symbol` and `steem.vests_symbol` as generic asset symbol names to improve the compatibility of beem with the Steemit testnet and other/third-party chains where the asset symbols are different to "STEEM", "SBD" or "VESTS".
The usage of the generic symbols is applied to various beem modules.
Changes in `beembase/operations.py` and `beembase/objects.py` propagate the corresponding prefix to the underlying objects for proper serialization also with the non-default chain parameters.

Using generic asset symbols

---

beem/discussions.py

Fixes #97 
- return if discussions are empty

Fix get_discussions infinite cycle when discussions are empty

---

beem/account.py

This adds an additional parameter to `get_recharge_timedelta`, `get_recharge_time` and `get_recharge_time_str`. `starting_voting_power` can be set optionally. The functions then return the time it needs until an account with `starting_voting_power` has reached `voting_power_goal`. If `starting_voting_power` is not set, it takes the account's current voting power

Adding additional parameter to recharge time calculations

---

beem/block.py

Fixes #122 
The `get_block()` answer contains the `block_id` field, correctly parsed by Block.block_num here:
https://github.com/holgern/beem/blob/49a8db878bff1a503b2e9acc9cd38f337efe9ba5/beem/block.py#L163
The `get_ops_in_block()` answer, however, does not contain a `block_id` field but directly provides the block number via the 'block' field. By adding a check for the `block` field, both cases should be treated correctly and Blockchain.blocks() doesn't run into `int(None)` errors anymore here:
https://github.com/holgern/beem/blob/49a8db878bff1a503b2e9acc9cd38f337efe9ba5/beem/blockchain.py#L470

block.py: handle .block_num for get_ops_in_block

---

beem/account.py

Switching `Account.get_vesting_delegations()` from the `find_vesting_delegations` API call, which is limited to only the first 1000 entries, to `list_vesting_delegations`. The latter supports `start_account` and `limit` also for appbase nodes and allows fetching all delegations also for accounts with more than 1000 delegations (e.g. `@steem`).

Account: support for retrieving all delegations

---

beem/cli.py

The shared `Steem` instance does not connect by default.`beempy createwallet` raised a `beemapi.exceptions.RPCConnection: RPC is not connected!`. `wallet.keyStorage.getPublicKeys(prefix=self.steem.prefix)` tries and fails to lookup the network prefix in the unconnected state.

connect for beempy createwallet

---

beem/cli.py

fixes #137 
The regular `Block.transactions()` call provides timestamps as `datetime` objects, which cannot be directly serialized with `.json()` and led to TypeErrors when loading the transactions with `TransactionBuilder`. Using `Block.json_transactions()` avoids this.

fix beempy verify --use-api

---

beem/block.py

Avoid BlockDoesNotExistsException on `blockchain.stream()` and `Block()` with `only_ops=True` on blocks without ops.
Fixes #149.
Returning a dict with the requested block number enables `blockchain.blocks()` to keep track of which blocks were handled already. Since there are no ops when this code branch is taken, the timestamp is irrelevant in this case.

fix empty block handling

---

beem/steem.py
tests/beem/test_steem.py

There was a typo in the `create_account` function related to `posting_authority_accounts`. This PR fixes the typo and updates the tests to help smoke out an issue like it in the future.
I was unable to run the test with `exclude_limited` in the nodelist so I removed it. Let me know if you want to leave that there and I can put it back in.

fix issue with adding posting auth to new accounts

---

beem/steem.py
beem/utils.py
tests/beem/test_steem.py
tests/beem/test_utils.py

* append timestamp also to root post permlinks to avoid overwriting existing
posts with the same title (fixes #179)
* avoid root permlinks to exceed the maximum length
* refactoring reply permlinks

improve permlink derivation

---

beem/account.py
beem/comment.py
beem/discussions.py
beem/snapshot.py
beem/steem.py

* Improving compatibility with various node formats, some have the data in `['discussions']` others directly - may need adjustments at more calls in discussions.py, but (mostly) works now for blog/comments/replies and comment.replies (see table below).
* fix parameters to reply_history
* Improve compatibility with condenser API (doesn't seem to like unused params supplied via `Query` - using dicts directly
* remove redundant API call for feed history in `Steem` constructor
* bugfix in snapshot/build_sp_arrayt for power-up to another account
| Node | Condenser | Call | Result |
| --- | --- | --- | --- |
| https://api.steemit.com | True | blog_history | pass |
| https://api.steemit.com | True | comment_history | pass |
| https://api.steemit.com | True | reply_history | pass |
| …

response format handling and minor other things

---

beem/steem.py
beemapi/rpcutils.py

* `beempy --node https://api.hive.blog claimaccount [accname]` led to `Could not find method get_resource_pool`, turned out the nodes accept `get_resource_pool` only in appbase format
* Hive was not detected as appbase-ready - added in rpcutils
* RC calculation used `STEEM_BLOCK_INTERVAL` - by switching to the existing `get_block_interval`, the same call also works with `HIVE_BLOCK_INTERVAL`

a few more mods for Hive compatibility

---

beem/snapshot.py
beembase/operationids.py
examples/account_vp_over_time.py

This enables the snapshot module to work even after the steem/hive fork. In order to do that, I needed to ignore the update_proposal_votes operation, and add the hardfork_hive operation for those accounts that are on the blacklist for the hardfork.
I also improved how the vp_arrays are built, so that longer voting pauses don't cause the graph to look like VP slowly regenerated, and that they also include the downvote VP after the time HF21 went live. I was told that at HF21 Downvote Power started at 100%, but I'm not entirely sure on that.

Snapshot update

---

beem/blockchain.py

Hi, `blockchain.stream(max_batch_size=50, only_virtual_ops=True)` fails with
```
File "/usr/local/lib/python3.6/site-packages/beem/blockchain.py", line 562, in blocks
block = block["ops"]
TypeError: list indices must be integers or slices, not str
```
It requires both `max_batch_size` and `only_virtual_ops` enabled to fail.
According to the [API](https://developers.hive.io/apidefinitions/#condenser_api.get_ops_in_block) the call is expected to return a list of transactions, not a dict with `ops` key (anymore?). The attached PR works around this and the same scheme is used at [other occasions](https://github.com/holgern/beem/blob/76d7f1cae5ee1288f725e111d2e074dc9d7cf50a/beem/block.py#L146) as well.
Reproduce via
```python
from beem import Hive
from beem.blockchain import Blockchain
h = …
```

blockchain.py: handle virtual ops batch streaming

---

beem/transactionbuilder.py

Fix for corner case where `last_irreversible_block_num == head_block_number`
then `int(dynBCParams["last_irreversible_block_num"]) + 1` does not exists
and `BlockHeader` throws error.

Fix "block does not exists" error in transaction builder in certain condition

---

beem/blockchain.py
tests/beem/test_blockchain.py

`get_account_reputations` called with the `first` parameter set was skipping the first result also for the first request in the loop, effectively missing one result.
- only skip the first result for follow-up requests
- add test case for `get_account_reputations()`
- replace `steem_instance` with `blockchain_instance`
- add test case for `get_account_count()`

blockchain: get_account_reputations fix for first

---

beem/cli.py

the previous `int(hbd_interest_rate * 100)` took the `hdb_interest_rate` as string a hundred times, leading to `struct.error: argument out of range`. casting to `float` first, plus a few whitespace removals...

beempy witnessproperties: fix interest rate options

---

beemapi/graphenerpc.py

when both `HIVE_CHAIN_ID` and `STEEM_CHAIN_ID` returns valid IDs, Hive should be selected as the preferred network.

Prioritize HIVE_CHAIN_ID property for the chain selection
