holgern/beem

beem/account.py
=> account.history_reverse() fix for TypeError

beembase/operations.py
Fixes #20
I think I got it working with both the `comment_options` and `beneficiaries` parameters...
=> Fix beneficiaries handling in Comment_options

beem/account.py, beem/steem.py, beem/vote.py, beemapi/graphenerpc.py, beemapi/steemnoderpc.py
New features:
* adding `account.get_creator()` to find the creator of a Steem account
* adding support for setting beneficiaries also via `steem.comment_options()`
* adding check for total beneficiary weight
Fixes:
* the `comment_options` parameters for `steem.post()` and `steem.comment_options()` were using different representations for `percent_steem_dollar` (0-100% vs. 0 - 10000). A common method to build the `comment_options` op makes this consistent for both.
Refactoring:
* reuse methods and values from `utils` and `constants` instead of repeating code patterns or hard coded values
* graphenerpc: make RPC methods independent from dict keys integer values/arithmetics
* minor code repetitions compacted
=> Account features + some fixes and refactorings

beem/blockchain.py
actually wait `limit` blocks before raising an exception
=> blockchain.awaitTxConfirmation() fix timeout

beem/account.py
=> estimate_virtual_op_count: avoid division by zero

beem/account.py
Fixes #36. More reliable convergence and therefore less RPC calls.
This uses a different algorithm compared to before: linear approximation for the first iteration and divide & conquer for the following iterations. This may still be tuned, but at least convergence is more reliable than before.
=> reworking account.estimate_virtual_op_num

beemgraphenebase/base58.py
Left this out of https://github.com/holgern/beem/pull/39
=> Add vit to known_formats

beem/steemconnect.py
=> fix SteemConnect TransactionBuilder example

beem/discussions.py
=> discussions: set steem inst. as keyword argument

beem/account.py
New account methods:
* `account.feed_history()`: show the account feed history
* `account.blog_history()`: show the account blog history, optionally hiding resteems
* `account.comment_history()`: show the recent comments done from an account
* `account.reply_history()`: show the recent replies received to posts/comments of an account
=> Adding account methods for feed, blog, comments and replies

beem/conveyor.py, beemgraphenebase/ecdsasig.py
reverting ecdsasig changes, adjusting Conveyor signing to work with the previous implementation.
=> rework Conveyor signing, revert ecdsasig changes

beem/blockchain.py
=> Fix Blockchain.get_transaction_hex() on appbase

beem/account.py
=> fix Account.get_tags_used_by_author on appbase

beem/steem.py
=> Fix vests_to_rshares (issue #66)

beem/account.py, beem/blockchain.py, beem/steem.py, beem/steemconnect.py, docs/beemgraphenebase.ecdasig.rst, docs/beemgraphenebase.ecdsasig.rst, docs/modules.rst
No actual changes - only formatting fixes (such as code blocks not being rendered because of missing whitespace)
=> Fix many documentation errors (based on error messages when building)

beemgraphenebase/base58.py, beemgraphenebase/chains.py
node: `wss://deals.weku.io:8190`
=> adding weku chain properties

beemgraphenebase/base58.py, beemgraphenebase/chains.py
Hi @holgern, 
We're working on a project for the European Commission called EFTG which uses the Steem blockchain. We find your library very useful and would like to contribute to it to have support with our custom chain. 
More information here 
https://steemit.com/utopian-io/@sorin.cristescu/european-financial-transparency-gateway
=> European Financial Transparency Gateway support in Beem

beem/cli.py
=> corrected typo

beem/discussions.py
Fixes #93 
- adds *author*, *before_date* params to Query class
- fixes input params
- updates docstring
=> Fix `Discussions_by_author_before_date` in `get_discussions`

beem/account.py
=> account.py: fix potential ZeroDivisionError

beem/account.py
=> remove debug print

beem/comment.py
The calculation of rewards for posts that already paid out was not correct:
`total_payout_value` is only the author share of the payout, it does not contain the curator and beneficiary shares: 
https://github.com/steemit/steem/blob/9b3b9ef22afdeac055ba808667ee29e4744d90a2/libraries/chain/database.cpp#L1658
As a result, `get_vote_with_curation()` and `get_curation_rewards()` did not work properly for posts that already paid out. I've removed the curation calculation for paid out posts for now. A reverse calculation from the individual weights and the `total_vote_weight` in relation to `curator_payout_value` is not possible because the `total_vote_weight` field is cleared after payout.
Additionally: crediting unclaimed rewards to the author only for HF<20
=> fix Comment reward calculations

beem/account.py, beem/blockchain.py
* account.py: adding `change_recovery_account()`
* blockchain.py: adding 
* `find_change_recovery_account_requests()` to find pending requests from individual accounts
* `list_change_recovery_account_requests()` to list any pending requests
=> Change recovery account / list recovery account change requests

beembase/objects.py
Witness update operations will otherwise fail.
=> Exclude sbd_interest_rate, as it is not present on the VIT blockchain

beemapi/graphenerpc.py, beembase/objects.py, beembase/operationids.py, beembase/operations.py, examples/wls_post.py
reference: https://whaleshares.io/@alexpmorris/fixed-python-libraries-for-wls-v2-5-compatibility
=> fixes compatibility issues with WhaleShares HF2 / v2.5

beem/snapshot.py
Excuse the small PR, I just saw the typo while browsing through the documentation.
=> Remove tiny typo

beem/account.py, beem/cli.py
This PR adds a function for managing your witness proxy to `account.py` and adds according functions to the CLI
=> Add witness proxy management functions

beem/cli.py
* add `try/except` around the `Comment` call, skip non-existing comments
* clean whitespaces in cli.py
=> beempy pending fix for deleted comments

beem/blockchain.py
- `blochchain.stream(start, stop, max_batch_size=50, only_virtual_ops=True)` was skipping the last block per batch, requesting the 2nd to last block twice per call (was using `blocknum` instead of `last_block`).
- Refactored that code part to remove the duplicate requests, with and without `add_to_queue` set, merged into one loop
- actually use the appbase call when appbase is supported
=> correct blockchain virtual op batch calls
